/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ibm_research_blockmap_CapiKvDevice */

#ifndef _Included_com_ibm_research_blockmap_CapiKvDevice
#define _Included_com_ibm_research_blockmap_CapiKvDevice
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ibm_research_blockmap_CapiKvDevice
 * Method:    create
 * Signature: (Ljava/lang/String;J)J
 */
JNIEXPORT jlong JNICALL Java_com_ibm_research_blockmap_CapiKvDevice_create
  (JNIEnv *, jclass, jstring, jlong);

/*
 * Class:     com_ibm_research_blockmap_CapiKvDevice
 * Method:    close
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_ibm_research_blockmap_CapiKvDevice_close
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_ibm_research_blockmap_CapiKvDevice
 * Method:    put
 * Signature: (JLjava/lang/String;Ljava/nio/ByteBuffer;I)V
 */
JNIEXPORT void JNICALL Java_com_ibm_research_blockmap_CapiKvDevice_put
  (JNIEnv *, jclass, jlong, jstring, jobject, jint);

/*
 * Class:     com_ibm_research_blockmap_CapiKvDevice
 * Method:    get
 * Signature: (JLjava/lang/String;Ljava/nio/ByteBuffer;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_ibm_research_blockmap_CapiKvDevice_get
  (JNIEnv *, jclass, jlong, jstring, jobject);

/*
 * Class:     com_ibm_research_blockmap_CapiKvDevice
 * Method:    delete
 * Signature: (JLjava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_ibm_research_blockmap_CapiKvDevice_delete
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     com_ibm_research_blockmap_CapiKvDevice
 * Method:    contains_key
 * Signature: (JLjava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_ibm_research_blockmap_CapiKvDevice_contains_1key
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     com_ibm_research_blockmap_CapiKvDevice
 * Method:    put_async
 * Signature: (JLjava/lang/String;Ljava/nio/ByteBuffer;ILcom/ibm/research/blockmap/Callback;)V
 */
JNIEXPORT void JNICALL Java_com_ibm_research_blockmap_CapiKvDevice_put_1async
  (JNIEnv *, jclass, jlong, jstring, jobject, jint, jobject);

/*
 * Class:     com_ibm_research_blockmap_CapiKvDevice
 * Method:    get_async
 * Signature: (JLjava/lang/String;Ljava/nio/ByteBuffer;Lcom/ibm/research/blockmap/Callback;)V
 */
JNIEXPORT void JNICALL Java_com_ibm_research_blockmap_CapiKvDevice_get_1async
  (JNIEnv *, jclass, jlong, jstring, jobject, jobject);

/*
 * Class:     com_ibm_research_blockmap_CapiKvDevice
 * Method:    delete_async
 * Signature: (JLjava/lang/String;Lcom/ibm/research/blockmap/Callback;)V
 */
JNIEXPORT void JNICALL Java_com_ibm_research_blockmap_CapiKvDevice_delete_1async
  (JNIEnv *, jclass, jlong, jstring, jobject);

/*
 * Class:     com_ibm_research_blockmap_CapiKvDevice
 * Method:    containsKey_async
 * Signature: (JLjava/lang/String;Lcom/ibm/research/blockmap/Callback;)V
 */
JNIEXPORT void JNICALL Java_com_ibm_research_blockmap_CapiKvDevice_containsKey_1async
  (JNIEnv *, jclass, jlong, jstring, jobject);

/*
 * Class:     com_ibm_research_blockmap_CapiKvDevice
 * Method:    get_iterator
 * Signature: (J)Ljava/util/Iterator;
 */
JNIEXPORT jobject JNICALL Java_com_ibm_research_blockmap_CapiKvDevice_get_1iterator
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class com_ibm_research_blockmap_CapiKvDevice_KeyIterator */

#ifndef _Included_com_ibm_research_blockmap_CapiKvDevice_KeyIterator
#define _Included_com_ibm_research_blockmap_CapiKvDevice_KeyIterator
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ibm_research_blockmap_CapiKvDevice_KeyIterator
 * Method:    next_key
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_ibm_research_blockmap_CapiKvDevice_00024KeyIterator_next_1key
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class com_ibm_research_blockmap_CapiKvDevice_Flag */

#ifndef _Included_com_ibm_research_blockmap_CapiKvDevice_Flag
#define _Included_com_ibm_research_blockmap_CapiKvDevice_Flag
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
